### ISSUE TITLE
Expose forceSSL parameter

### ISSUE THREAD

**Issue by tmcw** [segmentio/integration-google-analytics#26]
The site I'm currently developing has a strict [Content Security Policy](http://www.html5rocks.com/en/tutorials/security/content-security-policy/) that we'd like to use to prevent non-https access to APIs. Google Analytics as a raw library has a `forceSSL` method we can use and we can include the snippet in SSL mode, but through segment it doesn't look like that option is exposed.

**Comment by f2prateek** [comment]
I think you'd need to open this against the https://github.com/segment-integrations/analytics.js-integration-google-analytics repo

**Comment by tmcw** [comment]
Ah, yeah - looks like [this ticket covers the problem](https://github.com/segment-integrations/analytics.js-integration-google-analytics/issues/4)
